### ISSUE TITLE
Melhora do desempenho

### ISSUE THREAD

**Issue by MarcPagliotto** [saulogm/advpl-excel#11]
Amigo, estou sentindo lentidão em planilhas com mais de 2500 linhas, existe alguma forma de melhorar a performance.?

Testei incluindo valores nas celulas com oTabela:Cell("E1_FILIAL"	,(cAliasXML)->E1_FILIAL) e depois com oExcel:Pos(1,1):SetValue((cAliasXML)->E1_FILIAL), nesse segundo exemplo um pouco mais rápido mas ainda com menor desempenho do que a classe FWMSExcel().

Tem como trabalha em desempenho?

**Comment by saulogm** [comment]
estou verificando isso, após eu aplicar melhorias para usar banco de dados ele caiu muito a performance. 
tenta usar essa versão que está bem rápido:
https://github.com/saulogm/advpl-excel/tree/0ed31367ced133ae9981ca313da7974da0ea776d

**Comment by saulogm** [comment]
Fiz um ajuste para gravar direto em arquivo, notei melhora de performance.

OBS: A função FWMSExcel usa memória para gravação, a gravação de muitos dados pode sobrecarregar o appserver , o arquivo final é muito grande e os recursos da função é mais limitado.

**Comment by saulogm** [comment]
sem retorno, fechando.
