### ISSUE TITLE
Multiple languages from SX3

### ISSUE THREAD

**Issue by elQuau** [saulogm/advpl-excel#13]
Hi, I changed some lines of your code to use it on different languages. Alias2Tab Line 6271:

do case
		case __LANGUAGE == 'SPANISH'
			cNomeCampo	:= allTrim(getSx3Cache(cCampo, 'X3_TITSPA'))
		case __LANGUAGE == 'ENGLISH'
			cNomeCampo	:= allTrim(getSx3Cache(cCampo, 'X3_TITENG'))
		otherwise
			cNomeCampo	:= allTrim(getSx3Cache(cCampo, 'X3_TITULO'))
	end

Best regards.

**Comment by saulogm** [comment]
Hi, better this way:
cNomeCampo	:= AllTrim(FWX3Titulo(cCampo))

**Comment by elQuau** [comment]
Great, thanks.
