### ISSUE TITLE
Não consegue pegar imagem do repositório do protheus

### ISSUE THREAD

**Issue by driorlovski** [saulogm/advpl-excel#14]
Estou tentando fazer um fonte meu pegar as imagens dos produtos no repósitórios do protheus através do campo B1_BITMAP, porém ele não consegue achar a imagem vinculada ao produto no repositório do protheus, vc tem alguma idéia de como fazer ele pegar a imagem através deste campo, no repositório do protheus?

**Comment by saulogm** [comment]
Veja https://tdn.totvs.com/display/framework/TBmpRep

vou fechar, pois aqui é apenas para dúvidas e erros da classe advpl excel. 👍
