### ISSUE TITLE
Desempenho do método MergeCell

### ISSUE THREAD

**Issue by gabriel-landeira** [saulogm/advpl-excel#15]
Saulo, parabéns pela classe e obrigado por disponibilizar ela, nos ajudou muito!

Usamos ela em um relatório de packing list para os nossos pedidos. Em alguns casos já tínhamos notado alguma lentidão, mas nada muito grande.

Agora geramos o relatório para um pedido bastante grande e o relatório levou 10 horas para gerar.

Avaliando o código, percebi que a lentidão acontece no método MergeCell. O tempo de execução dele cresce exponencialmente com o relatório. Nesse caso foram necessários mais de 10 mil merges, por isso o tempo.

Ao avaliar o código do método, vi que a lentidão ocorre na validação se a célula já teve um merge.
Comentei esse trecho do código e o relatório gerou em 2 minutos.

Seria possível alguma melhora no desempenho desse método?
Pensei em talvez validar a duplicidade do merge apenas ao final do relatório e não a cada nova instrução.

**Comment by saulogm** [comment]
Olá Gabriel,
Obrigado pelo comentário, que bom que está sendo útil para você.

Pergunta você está utilizando a ultima versão? liberei algo recente da classe.

De qualquer forma eu vou avaliar a mudança e responder aqui. Talvez implementar um ThashMap para guardar os merge.

Outra coisa, se puder indicar as linhas que você comentou e obteve melhora na função, também ajudaria.

**Comment by gabriel-landeira** [comment]
Sim, atualizei para a ultima versão antes de efetuar o debug.

Comentei da linha 2829 até a 2839.


```
aChildren	:= ::asheet[::nPlanilhaAt][1]:XPathGetChildArray( "/xmlns:worksheet/xmlns:mergeCells" )
For nCont:=1 to Len(aChildren)
	cAtrr	:= ::asheet[::nPlanilhaAt][1]:XPathGetAtt(aChildren[nCont][2],"ref")
	If Replace(cColuna+cValToChar(nLinha),"$","") $ Replace(cAtrr,"$","") .OR. Replace(cColuna2+cValToChar(nLinha2),"$","") $ Replace(cAtrr,"$","")
		nPos	:= nCont
		Exit
	Endif
Next
If nPos>0
	UserException("YExcel - metodo mergeCells. C�lula "+cColuna+cValToChar(nLinha)+":"+cColuna2+cValToChar(nLinha2)+" n�o pode ser mesclada, essa c�lula j� foi mesclada!")
Endif
```

Inclusive testei depois removendo apenas o laço, deixando ainda a primeira linha que busca o aChildren. Mas o tempo voltou a ficar alto. Não tanto com o laço, mas ainda impraticável. Conclui que o método XPathGetChildArray também tem o tempo aumentando de forma exponencial, bem como o número de iterações do laço.

**Comment by saulogm** [comment]
Fiz um ajuste usando o ThashMap, veja se o tempo para gerar o Excel ficou aceitável. 

PS: Corrigi também a formatação condicional.

https://github.com/saulogm/advpl-excel/blob/master/src/YEXCEL.prw

**Comment by gabriel-landeira** [comment]
Bom dia Saulo.

Fiz os teste aqui e o desempenho ficou excelente, Na verdade ficou praticamente o mesmo do que estava com a validação comentada.

Não conhecia essa classe tHashMap, vou dar uma estudada nela para otimizar alguns processos aqui.
Muito obrigado!

**Comment by saulogm** [comment]
Show!
