### ISSUE TITLE
YExcel - não grava texto somente numeros

### ISSUE THREAD

**Issue by paulosoaresr** [saulogm/advpl-excel#16]
Estou fazendo testes com a classe e a mesma não esta gravando os textos somente valores numericos

**Comment by saulogm** [comment]
Olá poderia enviar um exemplo pequeno de como está sendo feito, para assim
analisar qual o problema.

**Comment by saulogm** [comment]
@paulosoaresr teste esse exemplo:
```advpl
Local oExcel := YExcel():new()
oExcel:ADDPlan() //Cria Planinha
oExcel:Pos(1,1):SetValue("Olá Mundo") //Escreve
oExcel:Save()    //Salvar
oExcel:OpenApp() //Abrir Excel
oExcel:Close()   //Fechar e limpar objeto
```

**Comment by paulosoaresr** [comment]
So funciona se eu deixar como M 
 
Local oExcel := YExcel():new(‘teste’,,’M’)
 
oExcel:ADDPlan() //Cria Planinha
 
oExcel:Pos(1,1):SetValue("Olá Mundo") //Escreve
 
oExcel:Save()    //Salvar
 
oExcel:OpenApp() //Abrir Excel
 
oExcel:Close()   //Fechar e limpar objeto

**Comment by saulogm** [comment]
Testei aqui e funcionou perfeitamente.

Build: 7.00.210324P-20220510 - 64 bits
Versão da lib: 20211004
Realease 12.1.033

Você compilou a ultima versão do [yexcel.prw](https://github.com/saulogm/advpl-excel/blob/master/src/YEXCEL.prw) ?

**Comment by saulogm** [comment]
sem resposta, fechando
