### ISSUE TITLE
Sugestao - Leitura XLSX: Valor Default

### ISSUE THREAD

**Issue by andremororo** [saulogm/advpl-excel#19]
Sugiro a seguinte implementação: Caso célula esteja em branco, deve ser atribuído como retorno de GetValue um valor vazio do tipo daquela célula.

OBS: Isto não pode impactar o cenário onde existem linhas vazias.

**Comment by saulogm** [comment]
Já completado conforme Wiki
https://github.com/saulogm/advpl-excel/wiki/method-getvalue
