### ISSUE TITLE
InterFunctionCall: cannot find function h_xls_sheet in AppMap

### ISSUE THREAD

**Issue by cicerocruz** [saulogm/advpl-excel#2]
Olá baixei a ultima versão e ao rodar o teste aparece a seguinte mensagem:

InterFunctionCall: cannot find function h_xls_sheet in AppMap

**Comment by saulogm** [comment]
Fiz um teste reaplicando o patch e o fonte compila normal
![compilacao](https://user-images.githubusercontent.com/5121888/51714808-365d5880-2015-11e9-8ea0-c0596d6188a4.png)

validating XLS_SHEET.APH
P12.1.17 [yexcel_P12.1.17.ptm](patch/yexcel_P12.1.17.ptm)

**Comment by saulogm** [comment]
Conseguiu fazer funcionar?

**Comment by cicerocruz** [comment]
Oi Apliquei o patch como solicitado ocorre que aparece a seguinte mensagem
ao  abrir o excel:

[image: image.png]

Creio que o excel esta  removendo a imagem...

Atenciosamente,



*Eng. Cicero Cruz*

Em sáb, 26 de jan de 2019 às 14:59, Saulo Martins <notifications@github.com>
escreveu:

**Comment by cicerocruz** [comment]
Segue a imagem:
![image](https://user-images.githubusercontent.com/9358487/51793109-579f7f80-21a2-11e9-920e-982fdbd59abd.png)

**Comment by nahimdhaney** [comment]
Bom día Saulo, pode disponibilizar o pacote no espanhol? TTTS? por gentileza, agradecería muito!
