### ISSUE TITLE
Help linhas e colunas

### ISSUE THREAD

**Issue by AndersonMarcus** [saulogm/advpl-excel#21]
Estou preenchendo linhas e colunas com valores de uma matriz, mas precisaria  a cada loop voltar o valor da Linha ao inicio e só mudar a coluna, só que do segundo loop em diante as linhas vão sendo somadas., qual parametro altero? já tentei adimension mas não deu certo

**Comment by saulogm** [comment]
O melhor é fazer isso primeiro em um tabela temporária para depois passar para o excel assim você vai ter melhor performance.

Agora se quiser pode iniciar em memoria a custo de memoria no servidor, se o arquivo não for grande pode ser um opção:

```advpl
Local oExcel := YExcel():new(,,"M")  //Inicia em memoria
oExcel:ADDPlan() //Cria Planinha
oExcel:Pos(1,1):SetValue("Olá Mundo") //Altera linha 1 coluna 1
oExcel:Pos(2,1):SetValue("Segunda linha") //Altera linha 2 coluna 1
oExcel:Pos(1,1):SetValue("Primeira linha") //Volta para linha 1 coluna 1
oExcel:Save()    //Salvar
oExcel:OpenApp() //Abrir Excel
oExcel:Close()   //Fechar e limpar objeto
```

**Comment by AndersonMarcus** [comment]
For i:= 1 to Len(aMatriz)
		nLinha := 2
		nColuna += 1
		For y:= 1 to Len(aMatriz[i])
			nLinha += 1
			oExcel:Pos(nLinha,nColuna):SetValue(aMatriz[i][y])
			//oExcel:Cell(nLinha,nColuna,aMatriz[i][y],,) //tentei desta forma tbm
		next
		next

Seria esse o codigo, no segundo loop, precisaria que voltasse ao valor inicial de nLinha, na coluna seguinte, precisaria que fosse dinâmico assim pois, tem uma condição anterior que dependendo da opção muda os valores.

**Comment by saulogm** [comment]
Pelo que entendi você quer preencher todas as linhas de uma coluna, voltar e preencher todas as linhas de outra coluna.
Pode ser feito, mas inicia o YExcel em memoria passando o terceiro parâmetro um "M"
```advpl
Local oExcel := YExcel():new(,,"M")  //Inicia em memoria
```

**Comment by AndersonMarcus** [comment]
Deu certo, muito Obrigado! só por curiosidade como crio a tabela temporária?

**Comment by saulogm** [comment]
https://tdn.totvs.com/display/public/framework/FWTemporaryTable
No final da pagina tem um exemplo

**Comment by AndersonMarcus** [comment]
Surgiu mais uma duvida, como faço pra mudar o nome do arquivo, pois ele gera um nome aleatório, preciso receber um nome vindo de uma variável.

**Comment by saulogm** [comment]
```advpl
Local oExcel := YExcel():new("nomedoarquivo",,"M")  //Se quiser controlar o nome a ser gerado enviar primeiro parâmetro sem a extensão

cDiretorio := "c:\temp" //Aqui você pode informar o diretório a ser gravado

cArquivoGerado := oExcel:Save(cDiretorio)  //cArquivoGerado vai retornar o caminho completo do arquivo c:\temp\nomedoarquivo.xlsx
```

**Comment by AndersonMarcus** [comment]
Obrigado deu certo, o método AddPane funciona quando executado em memória? esta dando erro quando vai abrir a planilha

**Comment by saulogm** [comment]
fiz um ajuste agora, favor pegar ultima versão e realizar um teste. Por favor informe aqui se deu certo.

**Comment by AndersonMarcus** [comment]
Permanece o problema, estou enviando um pedaço do codigo pra vc ver se não to fazendo errado tbm

// Início do cabeçalho
	oExcel:Cell(1,1,cTemplateAlt,,nTabStyTit)
	oExcel:Cell(2,1,"Código",,nTabStySub)
	oExcel:AddTamCol(1,2,16.00)

//Define dinâmicamente as colunas da planilha
	For x:= 1 to Len(aColuns)
	
		nColuna += 1
		//oExcel:Pos(2,nColuna):SetValue(acoluns[x])
		oExcel:Cell(2,nColuna,acoluns[x],,nTabStySub)
		oExcel:AddTamCol(2,nColuna,15.00)
		
	next
		nCol := nColuna
	
	
//Define dinâmicamente as linhas da primeira coluna de códigos
	nColuna := 1
	nLinha := 2
	For i:= 1 to Len(aCodigos)
		nLinha := 2
		For y:= 1 to Len(aCodigos[i])

			nLinha += 1
			//oExcel:Pos(nLinha,nColuna):SetValue(aCodigos[i][y])
			oExcel:Cell(nLinha,nColuna,aCodigos[i][y],,nTabDetBor)
		next
	next

//Define dinâmicamente valores linhas em suas colunas 
	nColuna := 1
	nLinha := 2
	For i:= 1 to Len(aMatriz)

		nLinha := 2
		nColuna += 1

		For y:= 1 to Len(aMatriz[i])

			nLinha += 1
			//oExcel:Pos(nLinha,nColuna):SetValue(aMatriz[i][y])
			oExcel:Cell(nLinha,nColuna,aMatriz[i][y],,nTabDetBor)

		next
	next

	oExcel:mergeCells(1, 1,1,nCol)//Mescla as celulas do cabeçalho
	oExcel:AutoFilter(2,1,2,nCol)
	//oExcel:AddPane(2,nCol)

**Comment by AndersonMarcus** [comment]
![image](https://user-images.githubusercontent.com/8527392/231528140-10cf798b-bdda-4c99-9b09-3692bc60a4d1.png)

**Comment by saulogm** [comment]
Não consigo analisar assim.
Se puder enviar o fonte completo e o arquivo gerado

**Comment by AndersonMarcus** [comment]
#INCLUDE` 'TOTVS.CH'

/*====================================================================================================================
{Protheus.doc}UNIR032
====================================================================================================================
	@description
	Relatório de Atributos dos Templates da CZG010*

	@author		Anderson
	@version	1.0
	@since		11/04/2023
====================================================================================================================
====================================================================================================================*/

User function testedb()

	Local aColuns := {}
	Local aArea      := GetArea()
	Local i			 := 1
	Local aQuery	 := {}
	Local aCodigos	 := {}
	Local nLinha 	 := 1
	Local nColuna 	 := 1
	Local nCol		 := 1
	Local y 		 := 1
	Local x 		 := 1
	Local dData 	 := DATE()
	Local cTemplate  := ""
	Private cArquivo := " "
	Private cPath       := " "

	If !Perguntas2()
		MsgAlert("Operação cancelada pelo Usuário")
		Return .F.
	EndIf


	// É definido o endereço em que o arquivo do Excel é salvo
	cPath            := cGetFile(, 'Escolha o local' ,0, 'C:\totvs' ,.T.,GETF_LOCALFLOPPY+GETF_LOCALHARD+GETF_NETWORKDRIVE+GETF_RETDIRECTORY,.F.)

	If cPath == ""
		MsgAlert("Operação cancelada pelo Usuário")
		Return .F.
	EndIf

// Verifica se o Excel está instalado na máquina
	If !ApOleClient("MSExcel")
		MsgAlert("Microsoft Excel não instalado!")
		Return
	EndIf

	cPergunta := AllTrim(MV_PAR01)

	dbSelectArea('CZE')
	//Posicione (Alias,indice, Filial, codigo, campo retorno)
	cTemplate            := cValToChar(Posicione("CZE",3 , xFilial("CZE")+ cPergunta,"CZE_CDMD"))
	('CZE')->(dbCloseArea())

	cTemplateAlt := Trim(cTemplate)
	cArquivo         := cTemplateAlt + "_" + dtos(dData)

	BeginSql Alias "Alias_z"

SELECT DISTINCT CZG_CDAB ATRIBUTOS
FROM CZG010 
WHERE D_E_L_E_T_ <> '*'
AND CZG_CDMD = %exp:cPergunta%

	EndSql

	While ("Alias_z")->(!Eof())
		nCol 		 := nCol +  1

		aadd(aColuns,("Alias_z")->ATRIBUTOS)

		("Alias_z")->(dbSkip())
	ENDDO

	("Alias_z")->(dbCloseArea())
	RestArea(aArea)

//Faz Select de acordo com a quantidade de itens do array aColuns
	aMatriz := {}
	for i := 1 to Len(aColuns)

		YTRE := GetNextAlias()
		BeginSql Alias YTRE

			SELECT CZG_CDAC CODIGO, CZG_VLNR VALOR 
			FROM CZG010 
			WHERE D_E_L_E_T_ <> '*'
			AND CZG_CDMD = %exp:cPergunta%
			AND CZG_CDAB =  %exp:aColuns[i]%
			ORDER BY CODIGO ASC

		EndSql
//Cria array dos aliases gerados na consulta	
		aadd(aQuery ,(YTRE))

	Next

//Varre os Aliases pegando os dados necessários e inserindo em uma matriz
	for y := 1 to Len(aQuery)
		dbselectarea(aQuery[y])
		aCols := {}
		aCod  := {}

		for x := 1 to Len(aQuery[y])


			While (aQuery[y])->(!Eof())

				aadd(aCod,(aQuery[y])->CODIGO)
				aadd(aCols,(aQuery[y])->VALOR)
				(aQuery[y])->(dbSkip())

			EndDo
		next
		aadd(aMatriz, aCols)

		(aQuery[y])->(dbCloseArea())
	next
	aadd(aCodigos, aCod)

//Nome da Aba
	cAba             := cPergunta
	oExcel           := YExcel():new(cArquivo,,"M" ) //cria tabela 

// Criação de nova aba
	oExcel:ADDPlan(cAba)

	oAlinTit	:=	oExcel:Alinhamento("center","center") //cHorizontal,cVertical,lReduzCaber,lQuebraTexto,ntextRotation
	oAlinSub	:=	oExcel:Alinhamento("center","center",.F.,.T.)
	oFontNeg	:= 	oExcel:AddFont(,,,,,.T.,,,)
	oAlinDet	:=	oExcel:Alinhamento("left","center",.F.,.T.)
	oFontBra	:= 	oExcel:AddFont(10,"FFFFFF",,,,.T.,,,)
	oCorAzul	:=	oExcel:CorPreenc("183884") // Azul UNIFAP
	nDetFont	:=	oExcel:AddFont(8,,,,,.T.,,,)
	nPosBorda	:= 	oExcel:Borda("ALL") //cTipo,cCor,cModelo
	nTitFont	:=	oExcel:AddFont(12,"000000","Calibri","2",,.T.,,,) //nTamanho,cCorRGB,cNome,cfamily,cScheme,lNegrito,lItalico,lSublinhado,lTachado
	nDetFont	:=	oExcel:AddFont(11,"000000","Calibri","2",,,,,)
	nTabStySub	:=	oExcel:AddStyles(,oFontBra,oCorAzul,,,{oAlinSub})
	nTabStydate :=  oExcel:AddStyles(,nDetFont,,,,{oAlinDet})
	nTabStyTit	:=	oExcel:AddStyles(,nTitFont,,nPosBorda,,{oAlinTit}) // oExcel:AddStyles(/*numFmtId*/,/*fontId*/,/*fillId*/,/*borderId*/,/*xfId*/,{Alinhamento})
	nTabDetBor	:= 	oExcel:AddStyles(,nDetFont,,nPosBorda,,{oAlinDet})

// Início do cabeçalho
	oExcel:Cell(1,1,cTemplateAlt,,nTabStyTit)
	oExcel:Cell(2,1,"Código",,nTabStySub)
	oExcel:AddTamCol(1,2,16.00)

//Define dinâmicamente as colunas da planilha
	For x:= 1 to Len(aColuns)
	
		nColuna += 1
		//oExcel:Pos(2,nColuna):SetValue(acoluns[x])
		oExcel:Cell(2,nColuna,acoluns[x],,nTabStySub)
		oExcel:AddTamCol(2,nColuna,15.00)
		
	next
		nCol := nColuna
	
	
//Define dinâmicamente as linhas da primeira coluna de códigos
	nColuna := 1
	nLinha := 2
	For i:= 1 to Len(aCodigos)
		nLinha := 2
		For y:= 1 to Len(aCodigos[i])

			nLinha += 1
			//oExcel:Pos(nLinha,nColuna):SetValue(aCodigos[i][y])
			oExcel:Cell(nLinha,nColuna,aCodigos[i][y],,nTabDetBor)
		next
	next

//Define dinâmicamente valores linhas em suas colunas 
	nColuna := 1
	nLinha := 2
	For i:= 1 to Len(aMatriz)

		nLinha := 2
		nColuna += 1

		For y:= 1 to Len(aMatriz[i])

			nLinha += 1
			//oExcel:Pos(nLinha,nColuna):SetValue(aMatriz[i][y])
			oExcel:Cell(nLinha,nColuna,aMatriz[i][y],,nTabDetBor)

		next
	next

	oExcel:mergeCells(1, 1,1,nCol)//Mescla as celulas do cabeçalho
	oExcel:AutoFilter(2,1,2,nCol)
	oExcel:AddPane(2,nCol)

	

	MsgInfo('Deu certo')

	oExcel:Save(cPath)    //Salvar
	oExcel:OpenApp() //Abrir Excel
	oExcel:Close()   //Fechar e limpar objeto
	//oExcel:Gravar(cPath,.T.,.F.) // Salve e abra o arquivo

	RestArea(aArea)

return

Static Function Perguntas2(cPerg)
	Local aPergs	:= {}
	Default cPerg	:= FunName()

	AADD(aPergs,{1,"Selecione o Template:"	,SPACE(6),"","","CZD001","",50,.T.}) // Tipo texto MV_PAR01

Return ParamBox(aPergs,"Parâmetros",{},,,,,,,cPerg,.F.,.F.)

**Comment by AndersonMarcus** [comment]
![image](https://user-images.githubusercontent.com/8527392/231544765-532e60ff-6def-4f03-9738-276060d85352.png)
cada retangulo é gerado dinamicamente, pegando os resultados das consultas ao banco de dados e armazenados em arrays

**Comment by saulogm** [comment]
manda o arquivo excel que deu o erro

**Comment by AndersonMarcus** [comment]
[LP_20230411.xlsx](https://github.com/saulogm/advpl-excel/files/11214512/LP_20230411.xlsx)

**Comment by saulogm** [comment]
esse arquivo não deu erro aqui, abriu corretamente no excel

**Comment by AndersonMarcus** [comment]
sim esse é o resultado sem a opção addpane estar ativa

**Comment by saulogm** [comment]
manda o arquivo com erro mesmo, com o addpane ativa

**Comment by AndersonMarcus** [comment]
[LP_20230412.xlsx](https://github.com/saulogm/advpl-excel/files/11214529/LP_20230412.xlsx)
esse apresenta o problema, foi gerado com addpane

**Comment by saulogm** [comment]
Por favor compilar ultima versão https://github.com/saulogm/advpl-excel/blob/master/src/YEXCEL.prw

**Comment by AndersonMarcus** [comment]
agora sim deu certo, muito obrigado pela atenção!
