### ISSUE TITLE
Erro ao anexar imagem ao excel

### ISSUE THREAD

**Issue by arnaldorjr** [saulogm/advpl-excel#22]
Boa tarde Saulo,

Antes de mais nada, parabéns pelo excelente trabalho. A sua classe YEXCEL é excelente.

Estou tentando adicionar uma imagem ao Excel, e ele não está reconhecendo a estrutura salva no xml após a conversão.
Efetuando debug do método addImg() constatei que ele faz todo o processo corretamente, copiando a imagem para o diretório no servidor, e adicionando na estrutura do XLM, mas ao abrir a planilha o Excel não reconhece a estrutura como válida, e ao resolver a estrutura ele "arranca" a imagem.

Você já se deparou com isso?

Desde já agradeço pela atenção.
Arnaldo R. Junior

**Comment by saulogm** [comment]
Bom dia,
Fiz testes aqui com a imagem e está ok.

Tem como colocar um exemplo simple de erro.

**Comment by saulogm** [comment]
Foi realizado um ajuste referente a usa mais de uma vez o método Img

**Comment by arnaldorjr** [comment]
Bom dia. Obrigado. Eu consegui entender o problema, mas farei um teste com
a versão mais atualizada do seu fonte. O problema ocorre quando vc tem duas
abas na planilha. Na 1a aba a imagem é inserida corretamente. Na 2a aba
ocorre o erro. Farei mais testes e enviarei um fonte simples de reproduzir.

Agradeço novamente pela atenção

Em ter., 19 de nov. de 2024 11:02, Saulo Martins ***@***.***>
escreveu:
