### ISSUE TITLE
Erro ao usar a classe em Job

### ISSUE THREAD

**Issue by gabriel-landeira** [saulogm/advpl-excel#23]
Bom dia Saulo.

Já faz algum tempo que usamos a classe para gerar relatórios em um Job, porém após a ultima atualização que fizemos no Protheus ela parou de funcionar.

O primeiro erro foi:
Invalid GetTempPath() client call in JOB. in file E:\build-dir\TP11-OF20310-TECXWIN64\interface\srvfunctions.inl at line 356
 on YEXCEL:SAVE(YEXCEL.PRW) 16/11/2023 08:47:46 line : 5777

Consegui contornar passando o caminho para salvar o arquivo na chamada do método Gravar().

Porém apareceu o segundo erro:
Function CpyS2T() isn't available in JOB. in file E:\build-dir\TP11-OF20310-TECXWIN64\advpl\arqdirfuncs.inl at line 433
 on YEXCEL:SAVE(YEXCEL.PRW) 16/11/2023 08:47:46 line : 6168

Aparentemente essas duas funções não podem ser usadas dentro de um Job. Tens alguma ideia do que poderia ser feito para contornar essa situação?

Abraço!

**Comment by saulogm** [comment]
Bom dia
Tente utilizar o Save passando um caminho do protheus data
```advpl
oExcel:Save("\tmp")
```

**Comment by gabriel-landeira** [comment]
Resolvido, obrigado Saulo!
