### ISSUE TITLE
Close()

### ISSUE THREAD

**Issue by developerviana** [saulogm/advpl-excel#25]
Boa tarde meu caro, tudo bem ? 

será que poderia me ajudar com está situação ?

Eu criei um fonte para ler arquivo XLSX e estou com um pequeno problema na hora de encerrar o programa..

sempre que meu programa entra na condição estipulada para finalizar como por EX:

    If !lMontikEncontrado .Or. !lKatriumEncontrado
        FWAlertWarning("A planilha selecionada não possui as celulas indicadoras de Preenchimento  'PREENCHIMENTO MONTIK' ou 'PREENCHIMENTO KATRIUM", "Não haverá processamento das informações para solicitação do packing list!") 
            oExcel:Close()
            Return
    EndIf

Na hora do return eu recebo o seguinte erro:

variable is not array - Type [U] on YEXCEL:GETVALUE(YEXCEL.PRW) 30/01/2024 15:43:08 line : 2605

**Comment by saulogm** [comment]
Boa noite,
Primeiro preciso que você atualize a sua versão do yexcel. Não tem como eu saber a versão que você está. Se o erro persistir, enviar o erro log completo.

**Comment by saulogm** [comment]
sem resposta
