### ISSUE TITLE
Geracao do pacote no otros idiomas 

### ISSUE THREAD

**Issue by nahimdhaney** [saulogm/advpl-excel#3]
Bom dia Saulo ,

por gentileza pode disponibilizar o pacote pra espanhol? TTTS na versão 12.1.17

Atenciosamente 

Nahim Terrazas - Bolivia

**Comment by saulogm** [comment]
Boa noite o pacote não tem tradução para outros idiomas, no caso ele é apenas uma ferramenta para gerar excel, não apresenta telas para o usuário final. Caso tenha dificuldade de aplicar o patch, sugiro baixar os o projeto completo e compilar todos os fontes.
