### ISSUE TITLE
Celular com borda e merge

### ISSUE THREAD

**Issue by danielAlbuquerque** [saulogm/advpl-excel#5]
Primeiramente parabens pelo projeto!

Eu não to encontrando uma forma de aplicar a borda em uma celula que possui merge, por exemplo o seguinte codigo gera o seguinte resultado:

![image](https://user-images.githubusercontent.com/6063722/83339380-a6cc5780-a2a3-11ea-95ec-f5d1983dfce0.png)

A borda esta sendo aplicada como se fosse apenas uma celula

![image](https://user-images.githubusercontent.com/6063722/83339384-b186ec80-a2a3-11ea-932b-47e8559c9c78.png)

**Comment by saulogm** [comment]
Olá Daniel,
Tente aplicar o estilo em todas as colunas e/ou linhas.

For nCont:=7 to 13
oExcel:Cell(1,nCont," ", ,nStyle1)
Next
For nCont:=7 to 13
oExcel:Cell(2,nCont," ", ,nStyle1)
Next

Depois vejo se coloco uma melhoria para não precisar disso.

**Comment by danielAlbuquerque** [comment]
Oi Saulo, nao deu certo, vc tem algum exemplo funcionando desse jeito?

**Comment by saulogm** [comment]
Aqui deu certo, veja:
![image](https://user-images.githubusercontent.com/5121888/83371123-e1172100-a397-11ea-93f3-2f569d963bba.png)

Ajustei o Exemplo com a borda em célula mesclada:
[tstyexcel.prw](exemplo/tstyexcel.prw)
