### ISSUE TITLE
Estilos não sendo aplicados

### ISSUE THREAD

**Issue by guilherme-nobrega** [saulogm/advpl-excel#6]
Ao aplicar um estilo ele não é aplicado, ele aplica o último estilo utilizado e não o que está sendo passado, no arquivo exemplo a primeira e quarta linha deveriam ter a cor de fundo da célula com a cor azul e fonte branca, porém é aplicada a cor branca na célula e fonte azul das linhas 2 e 3.

Testado no Protheus 12.1.025 e 23 um com dicionário no banco e outro não respectivamente.

[MenuTest.zip](https://github.com/saulogm/advpl-excel/files/4832360/MenuTest.zip)

**Comment by guilherme-nobrega** [comment]
Somente uma célula, a mesclada saiu com a formatação correta na foto de exemplo.

Desde já agradeço pelo projeto muito bom e empolgante algo do tipo, parabéns !

![Capturar](https://user-images.githubusercontent.com/50680134/85753150-5ef1f200-b6e2-11ea-93b5-5c248516a399.PNG)

**Comment by saulogm** [comment]
Guilherme Boa tarde,
No Advpl existe a limitação do tamanho da variável de 10, sendo desprezado o restante para variáveis grande.
nCalibri20BraAzulLCF -> Ele vai considerar nCalibri20
nCalibri10BraAzulCCT ->Ele vai considerar nCalibri10
nCalibri10BraAzulLCF -> Ele vai considerar nCalibri10

Veja se é esse o seu problema e me retorne.

**Comment by saulogm** [comment]
Após ajuste no tamanho das variáveis.
![image](https://user-images.githubusercontent.com/5121888/85780636-36c2bd00-b6fb-11ea-84ec-babbcc7d5ef6.png)

**Comment by guilherme-nobrega** [comment]
Correto, testes feitos e ajustados, tudo funcionando normalmente, estou começando ainda, vlw pela força !
