### ISSUE TITLE
Carregar imagens em um arquivo

### ISSUE THREAD

**Issue by guilherme-nobrega** [saulogm/advpl-excel#7]
Ao tentar adicionar mais de uma imagem ele carrega a mesma imagem repetida diversas vezes, não há suporte para mais de uma imagem no mesmo arquivo ? 
Testado no Protheus 12.1.025 e 23 um com dicionário no banco e outro não respectivamente.
[MenuTest.zip](https://github.com/saulogm/advpl-excel/files/4870345/MenuTest.zip)

[teste.zip](https://github.com/saulogm/advpl-excel/files/4870346/teste.zip)

Segue fontes e imagens

**Comment by saulogm** [comment]
Guilherme obrigado por reportar o problema.
Foi realizado um ajuste no fonte para pegar o ID correto da imagem.
Baixe uma nova versão e compile.
https://github.com/saulogm/advpl-excel/blob/master/src/YEXCEL.prw

PS: Estou trabalhando em atualizações desse projeto e logo que concluído liberarei melhorias e novas funcionalidade.

**Comment by guilherme-nobrega** [comment]
Certo, testado e funcionando já, vlw ! No aguardo para as melhorias !
