### ISSUE TITLE
Uso da função EncodeUTF8()

### ISSUE THREAD

**Issue by marcos-abrahao** [saulogm/advpl-excel#8]
Nas proximidades da linha 3657, não está sendo testado a chamada a funcão EncodeUTF8(aString[nCont][1])  retornar NIL, causando erro na linha se a conversão para UTF8 falhar.

**Comment by marcos-abrahao** [comment]
THREAD ERROR ([3708], adalberto.xavier, BKCSNOTAS0564)   14/07/2020 11:13:31
type mismatch on +  on YEXCEL:XLS_SHAREDSTRINGS(YEXCEL.PRW) 11/06/2020 09:34:58 line : 3657

**Comment by saulogm** [comment]
Oi Marcos
Poderia me passar como simular esse problema.
Se você já conseguiu identificar como solucionar esse problema também seria bem vindo.

A principio essa lista do tHashMap da linha 2657 deveria ter apenas caracteres, não fazendo sentido eu verificar o seu conteúdo.

**Comment by marcos-abrahao** [comment]
Boa tarde!
Uma tabela continha a string "LINDICÃ�SSIA SILVA DE CASTRO " e ocasionou o erro.
Fiz o seguinte para contornar:

Method xls_sharedStrings(nFile) class YExcel
	Local nCont
	Local aString
	Local cRet	:= ""
	Local cEncod:= ""
	::oString:list(@aString)
	aSort(aString,,,{|x,y| x[2]<y[2] })
	cRet	+= '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
	cRet	+= '<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="'+cValToChar(Len(aString))+'" uniqueCount="'+cValToChar(Len(aString))+'">'
	FWRITE(nFile,cRet)
	cRet	:= ""
	For nCont:=1 to Len(aString)
		cRet	+= '<si>'
		cEncod := EncodeUTF8(aString[nCont][1])
		If cEncod == Nil
			MsgStop(aString[nCont][1],"Yexcel")
			cEncod := ""
		EndIf
		cRet	+= '<t><![CDATA['+cEncod+']]></t>'
		cRet	+= '</si>'
		FWRITE(nFile,cRet)
		cRet	:= ""
	Next
	cRet	+= '</sst>'
	FWRITE(nFile,cRet)
	cRet	:= ""
Return cRet

**Comment by saulogm** [comment]
Com base na sua sugestão fiz o seguinte ajuste. Já subir para a versão principal.
```advpl
		cTexto	:= EncodeUTF8(aString[nCont][1])
		If Valtype(cTexto)!="C"
			cTexto	:= aString[nCont][1]
			cTexto	:= Replace(cTexto,chr(129),"")
			cTexto	:= Replace(cTexto,chr(141),"")
			cTexto	:= Replace(cTexto,chr(143),"")
			cTexto	:= Replace(cTexto,chr(144),"")
			cTexto	:= Replace(cTexto,chr(157),"")
			cTexto	:= EncodeUTF8(cTexto)
			If Valtype(cTexto)!="C"
				cTexto	:= ""
			EndIf
		EndIf
		cRet	+= '<t><![CDATA['+cTexto+']]></t>'
```
ajustado.

**Comment by marcos-abrahao** [comment]
Obrigado Saulo! Perfeito!
