### ISSUE TITLE
Erro ao executar o exemplo

### ISSUE THREAD

**Issue by ghost** [saulogm/advpl-excel#9]
Ao executar para testes, gerou erro na linha 6338.
Não consegui identificar o motivo.

Agradeço a ajuda.

**Comment by saulogm** [comment]
pode ser que ele não conseguiu ler o arquivo Excel. 
Pode colocar mais detalhes.

**Comment by saulogm** [comment]
sem mais detalhes não tem como analisar, tente atualizar a função.
